import { Recipe } from "./recipeType";

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Bolo de Chocolate',
    description: 'Um delicioso bolo de chocolate fofinho e úmido',
    category: 'Sobremesas',
    prepTime: 20,
    cookTime: 40,
    servings: 8,
    difficulty: 'Fácil',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    ingredients: [
      '2 xícaras de farinha de trigo',
      '1 xícara de chocolate em pó',
      '2 xícaras de açúcar',
      '4 ovos',
      '1 xícara de leite',
      '1/2 xícara de óleo',
      '1 colher de sopa de fermento em pó',
    ],
    instructions: [
      'Pré-aqueça o forno a 180°C',
      'Em uma tigela, misture os ovos, o açúcar e o óleo',
      'Adicione o leite e misture bem',
      'Acrescente a farinha, o chocolate em pó e misture',
      'Por último, adicione o fermento e misture delicadamente',
      'Despeje em uma forma untada e enfarinhada',
      'Asse por 40 minutos ou até que o palito saia limpo',
    ],
    isFavorite: false,
  },
  {
    id: '2',
    title: 'Frango Assado com Batatas',
    description: 'Frango suculento assado com batatas temperadas',
    category: 'Pratos Principais',
    prepTime: 15,
    cookTime: 60,
    servings: 4,
    difficulty: 'Médio',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop',
    ingredients: [
      '1 frango inteiro (aproximadamente 1,5kg)',
      '6 batatas médias',
      '4 dentes de alho',
      '2 limões',
      'Azeite de oliva',
      'Sal e pimenta a gosto',
      'Ervas (alecrim, tomilho)',
    ],
    instructions: [
      'Tempere o frango com sal, pimenta, alho e suco de limão',
      'Deixe marinar por pelo menos 30 minutos',
      'Pré-aqueça o forno a 200°C',
      'Corte as batatas em rodelas e tempere com sal, pimenta e azeite',
      'Disponha as batatas em uma assadeira',
      'Coloque o frango sobre as batatas',
      'Asse por 60 minutos ou até dourar',
    ],
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Salada Caesar',
    description: 'Clássica salada Caesar com molho cremoso',
    category: 'Saladas',
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: 'Fácil',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop',
    ingredients: [
      '1 pé de alface romana',
      '100g de queijo parmesão ralado',
      'Croutons',
      '2 filés de frango grelhado (opcional)',
      'Para o molho:',
      '2 colheres de maionese',
      '1 colher de mostarda Dijon',
      'Suco de 1/2 limão',
      '2 dentes de alho',
      'Sal e pimenta',
    ],
    instructions: [
      'Lave e corte a alface em pedaços',
      'Prepare o molho misturando maionese, mostarda, limão, alho, sal e pimenta',
      'Em uma tigela grande, misture a alface com o molho',
      'Adicione o queijo parmesão ralado',
      'Acrescente os croutons',
      'Se desejar, adicione o frango grelhado cortado em tiras',
      'Sirva imediatamente',
    ],
    isFavorite: false,
  },
  {
    id: '4',
    title: 'Spaghetti à Carbonara',
    description: 'Autêntica receita italiana de carbonara',
    category: 'Massas',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Médio',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=300&fit=crop',
    ingredients: [
      '400g de spaghetti',
      '200g de bacon em cubos',
      '4 gemas de ovo',
      '100g de queijo parmesão ralado',
      '50g de queijo pecorino ralado',
      'Pimenta preta moída na hora',
      'Sal a gosto',
    ],
    instructions: [
      'Cozinhe o spaghetti em água fervente com sal',
      'Em uma frigideira, frite o bacon até ficar crocante',
      'Em uma tigela, misture as gemas com os queijos ralados',
      'Escorra a massa, reservando 1 xícara da água do cozimento',
      'Adicione a massa quente à tigela com os ovos e queijos',
      'Misture rapidamente, adicionando água do cozimento se necessário',
      'Adicione o bacon e finalize com pimenta preta moída na hora',
    ],
    isFavorite: true,
  },
  {
    id: '5',
    title: 'Brigadeiro',
    description: 'Doce brasileiro tradicional',
    category: 'Sobremesas',
    prepTime: 5,
    cookTime: 15,
    servings: 20,
    difficulty: 'Fácil',
    imageUrl: 'https://images.unsplash.com/photo-1606312619070-d48b4ceb6bf4?w=400&h=300&fit=crop',
    ingredients: [
      '1 lata de leite condensado (395g)',
      '1 colher de sopa de manteiga',
      '3 colheres de sopa de chocolate em pó',
      'Chocolate granulado para decorar',
    ],
    instructions: [
      'Em uma panela, misture o leite condensado, a manteiga e o chocolate em pó',
      'Leve ao fogo médio, mexendo sempre',
      'Cozinhe até que a mistura desgrude do fundo da panela',
      'Despeje em um prato untado com manteiga',
      'Deixe esfriar completamente',
      'Unte as mãos com manteiga e enrole os brigadeiros',
      'Passe no chocolate granulado',
    ],
    isFavorite: true,
  },
  {
    id: '6',
    title: 'Smoothie de Frutas Vermelhas',
    description: 'Smoothie refrescante e nutritivo',
    category: 'Bebidas',
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    difficulty: 'Fácil',
    imageUrl: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400&h=300&fit=crop',
    ingredients: [
      '1 xícara de morangos congelados',
      '1/2 xícara de mirtilos congelados',
      '1 banana',
      '1 xícara de leite ou leite vegetal',
      '1 colher de sopa de mel',
      '1/2 xícara de iogurte natural',
    ],
    instructions: [
      'Coloque todos os ingredientes no liquidificador',
      'Bata até ficar homogêneo',
      'Se necessário, adicione mais leite para ajustar a consistência',
      'Sirva imediatamente',
    ],
    isFavorite: false,
  },
];
